const bolos = [
    {
        id: 1, nome: "Brigadeiro Gourmet",
        imagem: "../imagens/img-bolo-brigadeiro-gourmet.png", 
        descricao: "Massa neutra recheio de mouse de ninho e brigadeiro gourmet cremoso com pedacinhos de chocolate.", 
        preco: 80.00, 
        categoria: "Tradicional",
    },
    {
        id: 2, 
        nome: "Ninho Trufado", 
        imagem: "imagens-bolo/img-bolo-ninho-trufado.png", 
        descricao: "Massa neutra com recheio de creme de ninho com pedacinhos de choclolate, trufa de chocolate meio amargo e cobertura de chantininho.", 
        preco: 80.00, 
        categoria: "Tradicional",
    },
    {
        id: 3, 
        nome: "Sonho De Valsa", 
        imagem: "imagens-bolo/img-bolo-sonho-de-valsa.png", 
        descricao: "Massa neutra, recheio ninho cremoso com pedaços de bombom e creme de avelã com cobertura de chantininho.", 
        preco: 80.00, 
        categoria: "Tradicional",
    },
    {
        id: 4, 
        nome: "Ninho Com Abacaxi", 
        imagem: "imagens-bolo/img-bolo-ninho-com-abacaxi.png", 
        descricao: "Massa neutra, com recheio de creme de ninho com pedaços de abacaxi caramelizados com cobertura de cantininho.", 
        preco: 80.00, 
        categoria: "Tradicional",
    },
    {
        id: 5, 
        nome: "Beijinho", 
        imagem: "imagens-bolo/img-bolo-beijinho.png", 
        descricao: "Massa neutra, com recheio de coco cremoso, creme de ninho e cobertura de  chantininho.", 
        preco: 80.00, 
        categoria: "Tradicional",
    },
    {
        id: 6, 
        nome: "Prestigio", 
        imagem: "imagens-bolo/img-bolo-prestigio.png", 
        descricao: "Massa de chocolate ou neutra, com recheio de coco cremoso e chocalate.", 
        preco: 88.00, 
        categoria: "Premium",
    },
    {
        id: 7, 
        nome: "Ameixa Com Coco", 
        imagem: "imagens-bolo/img-bolo-ameixa-com-coco.png", 
        descricao: "Massa neutra recheado com coco cremoso e ameixas.", 
        preco: 88.00, 
        categoria: "Premium",
    },
    {
        id: 8, 
        nome: "Dois Amores", 
        imagem: "imagens-bolo/img-bolo-dois-amores.png", 
        descricao: "Massa neutra, com recheio de brigadeiro gourmet branco e brigadeiro gourmet tradicional.", 
        preco: 88.00, 
        categoria: "Premium",
    },
    {
        id: 9, 
        nome: "Lacta & Diamante Negro", 
        imagem: "imagens-bolo/img-bolo-lacta-diamante-negro.png", 
        descricao: "Massa neutra, com uma camada de creme de lacta branco aveludado e uma camada de creme de diamante negro com pedacinhos de chocolate.", 
        preco: 88.00, 
        categoria: "Premium",
    },
    {
        id: 10, 
        nome: "Chocolatudo", 
        imagem: "imagens-bolo/img-bolo-chocolatudo.png", 
        descricao: "Massa de chocolate recheado com mousse de chocolate e brigadeiro.", 
        preco: 95.00, 
        categoria: "Especial",
    },
    {
        id: 11, 
        nome: "Chef's Cake", 
        imagem: "imagens-bolo/img-bolo-chefs-cake.png", 
        descricao: "Massa de chocolate recheado de mousse de chocolate, trufa meio amarga e pedaços de morangos.", 
        preco: 95.00, 
        categoria: "Especial",
    },
    {
        id: 12, 
        nome: "Abacaxi Com Coco e Ninho", 
        imagem: "imagens-bolo/img-bolo-abacaxi-com-coco-e-ninho.png", 
        descricao: "Massa neutra, com creme de minho, coco cremoso e pedaços de abacaxi caramelizados.", 
        preco: 95.00, 
        categoria: "Especial",
    },
    {
        id: 13, 
        nome: "Ninho Com Morango", 
        imagem: "imagens-bolo/img-bolo-ninho-com-morango.png", 
        descricao: "Massa neutra, com recheio de creme de ninho com pedaços de morangos.", 
        preco: 95.00, 
        categoria: "Especial",
    },
    {
        id: 14, 
        nome: "Ninho Com Morango e Brigadeiro", 
        imagem: "imagens-bolo-ninho-com-morango-e-brigadeiro.png", 
        descricao: "Massa neutra, com recheio de creme de ninho com pedaços de morangos e brigadeiros gourmet.", 
        preco: 95.00, 
        categoria: "Especial"
    }
]